### 1 PDF
POST {{host}}/api/v1/pdf-merger-api
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; filename="dummy.pdf"
Content-Type: application/pdf

< ../pdf/dummy1.pdf
--WebAppBoundary--
### x PDF
POST {{host}}/api/v1/pdf-merger-api
Content-Type: multipart/form-data; boundary=Boundary

--Boundary
Content-Disposition: form-data; name="metadata"
Content-Type: text/plain

{"destination": "{{destination}}"}
--Boundary
Content-Disposition: form-data; filename="dummy1.pdf"
Content-Type: application/pdf

< ../pdf/dummy1.pdf
--Boundary
Content-Disposition: form-data; filename="dummy2.pdf"
Content-Type: application/pdf

< ../pdf/dummy2.pdf
--Boundary--