POST {{host}}/api/v1/pdf-merger-api
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="metadata"
Content-Type: text/plain

{"destination": "{{destination}}"}
--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="Hello.pdf"
Content-Type: application/octet-stream

{{pdfResource}}
--WebAppBoundary--
###

POST {{host}}/api/v1/pdf-merger-api
Content-Type: multipart/form-data; boundary=Boundary

--Boundary
Content-Disposition: form-data; name="metadata"
Content-Type: text/plain

{"destination": "{{destination}}"}
--Boundary
Content-Disposition: form-data; name="files"; filename="first.pdf"
Content-Type: application/pdf

{{pdfResource}}
--Boundary
Content-Disposition: form-data; name="files"; filename="second.pdf"
Content-Type: application/pdf

{{pdfResource}}
--Boundary--